using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Enrollment.Models;

namespace Enrollment.DAL
{
#if DEBUG
    public class EnrollmentInitializer : System.Data.Entity.CreateDatabaseIfNotExists<EnrollmentContext>
#else
    public class EnrollmentInitializer : System.Data.Entity.CreateDatabaseIfNotExists<EnrollmentContext>
#endif
    {
        protected override void Seed(EnrollmentContext context)
        {
            var genders = new List<Gender>
            {
                new Gender{GenderID = 2, GenderName = "Male"},

                new Gender{GenderID = 1, GenderName = "Female"}
            };
            genders.ForEach(s => context.Genders.Add(s));
            context.SaveChanges();

            var relationshiptypes = new List<RelationshipType>
            {
                new RelationshipType{RelationshipTypeID = 1, RelationshipTypeName = "Members Aunt", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 2, RelationshipTypeName = "Members Brother", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 3, RelationshipTypeName = "Cousin", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 4, RelationshipTypeName = "Daughter", DependBenefitsDropDown = true, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 5, RelationshipTypeName = "Domestic Part", DependBenefitsDropDown = true, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 6, RelationshipTypeName = "Estate", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 7, RelationshipTypeName = "Ex-spouse", DependBenefitsDropDown = true, DependPensionDropDown = true, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 8, RelationshipTypeName = "Members Father", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 9, RelationshipTypeName = "Fiancee", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 10, RelationshipTypeName = "Members Friend", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 11, RelationshipTypeName = "GrandDaughter", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 12, RelationshipTypeName = "Members GrandParent", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 13, RelationshipTypeName = "GrandSon", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 14, RelationshipTypeName = "Nurse member", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = false},
                new RelationshipType{RelationshipTypeID = 15, RelationshipTypeName = "Members Mother", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 16, RelationshipTypeName = "Members Nephew", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 17, RelationshipTypeName = "Members Niece", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 18, RelationshipTypeName = "Other Beneficiary", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 19, RelationshipTypeName = "Members Other relative", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 20, RelationshipTypeName = "Parents", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 21, RelationshipTypeName = "Religious Institution", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 22, RelationshipTypeName = "Members Significant Other", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 23, RelationshipTypeName = "Members Sister", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 24, RelationshipTypeName = "Son", DependBenefitsDropDown = true, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 25, RelationshipTypeName = "Spouse", DependBenefitsDropDown = true, DependPensionDropDown = true, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 26, RelationshipTypeName = "Step Child", DependBenefitsDropDown = true, DependPensionDropDown = false, BeneficDropDown = false},
                new RelationshipType{RelationshipTypeID = 27, RelationshipTypeName = "Members StepBrother", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 28, RelationshipTypeName = "StepDaughter", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 29, RelationshipTypeName = "Members StepFather", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 30, RelationshipTypeName = "Members StepMother", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 31, RelationshipTypeName = "Members StepSister", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 32, RelationshipTypeName = "Trustee", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 33, RelationshipTypeName = "Members Uncle", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 34, RelationshipTypeName = "Unknown", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = false},
                new RelationshipType{RelationshipTypeID = 35, RelationshipTypeName = "Ward", DependBenefitsDropDown = true, DependPensionDropDown = false, BeneficDropDown = true},
                new RelationshipType{RelationshipTypeID = 36, RelationshipTypeName = "Travis Cobra Type 2", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = false},
                new RelationshipType{RelationshipTypeID = 37, RelationshipTypeName = "Travis Cobra Type 2", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = false},
                new RelationshipType{RelationshipTypeID = 39, RelationshipTypeName = "Travis Cobra Type 1", DependBenefitsDropDown = false, DependPensionDropDown = false, BeneficDropDown = false}
            };
            relationshiptypes.ForEach(s => context.RelationshipTypes.Add(s));
            context.SaveChanges();

            var states = new List<State>
            {
                new State{StateID = 1, StateAbbreviation = "AA", StateName = "MILITARY: Americas"},
                new State{StateID = 2, StateAbbreviation = "AE", StateName = "MILITARY:Middle East, Europe, Canada"},
                new State{StateID = 3, StateAbbreviation = "AK", StateName = "Arkansas"},
                new State{StateID = 4, StateAbbreviation = "AL", StateName = "Alabama"},
                new State{StateID = 5, StateAbbreviation = "AP", StateName = "MILITARY: Pacific"},
                new State{StateID = 6, StateAbbreviation = "AR", StateName = "Arkansas"},
                new State{StateID = 65, StateAbbreviation = "AS", StateName = "American Samoa"},
                new State{StateID = 7, StateAbbreviation = "AZ", StateName = "Arizona"},
                new State{StateID = 10, StateAbbreviation = "CA", StateName = "California"},
                new State{StateID = 12, StateAbbreviation = "CO", StateName = "Colorado"},
                new State{StateID = 13, StateAbbreviation = "CT", StateName = "Connecticutt"},
                new State{StateID = 14, StateAbbreviation = "DC", StateName = "Distric of Columbia"},
                new State{StateID = 15, StateAbbreviation = "DE", StateName = "Delaware"},
                new State{StateID = 16, StateAbbreviation = "FL", StateName = "Florida"},
                new State{StateID = 17, StateAbbreviation = "GA", StateName = "Georgia"},
                new State{StateID = 66, StateAbbreviation = "GU", StateName = "Guam"},
                new State{StateID = 18, StateAbbreviation = "HI", StateName = "Hawaii"},
                new State{StateID = 19, StateAbbreviation = "IA", StateName = "Iowa"},
                new State{StateID = 20, StateAbbreviation = "ID", StateName = "Idaho"},
                new State{StateID = 21, StateAbbreviation = "IL", StateName = "Illinois"},
                new State{StateID = 22, StateAbbreviation = "IN", StateName = "Indiana"},
                new State{StateID = 23, StateAbbreviation = "KS", StateName = "Kansas"},
                new State{StateID = 24, StateAbbreviation = "KY", StateName = "Kentucky"},
                new State{StateID = 25, StateAbbreviation = "LA", StateName = "Louisiana"},
                new State{StateID = 26, StateAbbreviation = "MA", StateName = "Massachusetts"},
                new State{StateID = 27, StateAbbreviation = "MD", StateName = "Maryland"},
                new State{StateID = 28, StateAbbreviation = "ME", StateName = "Maine"},
                new State{StateID = 29, StateAbbreviation = "MI", StateName = "Michigan"},
                new State{StateID = 30, StateAbbreviation = "MN", StateName = "Minnesota"},
                new State{StateID = 31, StateAbbreviation = "MO", StateName = "Missouri"},
                new State{StateID = 67, StateAbbreviation = "MP", StateName = "Northern Mariana Islands"},
                new State{StateID = 32, StateAbbreviation = "MS", StateName = "Mississippi"},
                new State{StateID = 33, StateAbbreviation = "MT", StateName = "Montana"},
                new State{StateID = 34, StateAbbreviation = "NC", StateName = "North Carlolina"},
                new State{StateID = 35, StateAbbreviation = "ND", StateName = "North Dakota"},
                new State{StateID = 36, StateAbbreviation = "NE", StateName = "Nebraska"},
                new State{StateID = 37, StateAbbreviation = "NH", StateName = "New Hampshire"},
                new State{StateID = 38, StateAbbreviation = "NJ", StateName = "New Jersey"},
                new State{StateID = 39, StateAbbreviation = "NM", StateName = "New Mexico"},
                new State{StateID = 41, StateAbbreviation = "NV", StateName = "Nevada"},
                new State{StateID = 42, StateAbbreviation = "NY", StateName = "New York"},
                new State{StateID = 43, StateAbbreviation = "OH", StateName = "Ohio"},
                new State{StateID = 44, StateAbbreviation = "OK", StateName = "Oklahoma"},
                new State{StateID = 47, StateAbbreviation = "OR", StateName = "Oregon"},
                new State{StateID = 48, StateAbbreviation = "PA", StateName = "Pennsylvania"},
                new State{StateID = 49, StateAbbreviation = "PR", StateName = "Puerto Rico"},
                new State{StateID = 68, StateAbbreviation = "PW", StateName = "Palau"},
                new State{StateID = 50, StateAbbreviation = "RI", StateName = "Rhode Island"},
                new State{StateID = 51, StateAbbreviation = "SC", StateName = "South carolina"},
                new State{StateID = 52, StateAbbreviation = "SD", StateName = "South Dakota"},
                new State{StateID = 53, StateAbbreviation = "TN", StateName = "Tennessee"},
                new State{StateID = 54, StateAbbreviation = "TX", StateName = "Texas"},
                new State{StateID = 57, StateAbbreviation = "UT", StateName = "Utah"},
                new State{StateID = 58, StateAbbreviation = "VA", StateName = "Virginia"},
                new State{StateID = 59, StateAbbreviation = "VI", StateName = "Virgin Islands"},
                new State{StateID = 60, StateAbbreviation = "VT", StateName = "Vermont"},
                new State{StateID = 61, StateAbbreviation = "WA", StateName = "Washington"},
                new State{StateID = 62, StateAbbreviation = "WI", StateName = "Wisconsin"},
                new State{StateID = 63, StateAbbreviation = "WV", StateName = "West Virginia"},
                new State{StateID = 64, StateAbbreviation = "WY", StateName = "Wyoming"},
            };
            states.ForEach(s => context.States.Add(s));
            context.SaveChanges();

            var maritalStatuses = new List<MaritalStatus>
            {
                new MaritalStatus{MaritalStatusID = 1, MaritalStatusName = "Divorced"},
                new MaritalStatus{MaritalStatusID = 2, MaritalStatusName = "Married"},
                new MaritalStatus{MaritalStatusID = 4, MaritalStatusName = "Single"},
                new MaritalStatus{MaritalStatusID = 5, MaritalStatusName = "Widowed"}
            };
            maritalStatuses.ForEach(s => context.MaritalStatuses.Add(s));
            context.SaveChanges();

            //SELECT 'new Employer{'
            //		+ 'EmployerID = ' + CONVERT(VARCHAR(3), Employer.EmployerID)
            //        + ', EmployerName = "' + Employer.Name + '"'
            //        + ', PlanType = ' + CASE EmployerCBA.EmpType WHEN 'B' THEN 'PlanType.Benefits' WHEN 'P' THEN 'PlanType.Pension' ELSE 'PlanType.Joint' END
            //        + '},'
            //FROM Employer INNER JOIN EmployerCBA ON Employer.EmpCode = EmployerCBA.EmpCode
            //WHERE Employer.Active = 1
            var employers = new List<Employer>
            {
                new Employer{EmployerID = 4, EmployerName = "Employer 01", PlanType = PlanType.Joint},
                new Employer{EmployerID = 7, EmployerName = "Employer 02", PlanType = PlanType.Joint},
                new Employer{EmployerID = 9, EmployerName = "Employer 03", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 10, EmployerName = "Employer 04", PlanType = PlanType.Joint},
                new Employer{EmployerID = 11, EmployerName = "Employer 05", PlanType = PlanType.Joint},
                new Employer{EmployerID = 16, EmployerName = "Employer 06", PlanType = PlanType.Joint},
                new Employer{EmployerID = 17, EmployerName = "Employer 07", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 19, EmployerName = "Employer 08", PlanType = PlanType.Joint},
                new Employer{EmployerID = 20, EmployerName = "Employer 09", PlanType = PlanType.Joint},
                new Employer{EmployerID = 22, EmployerName = "Employer 10", PlanType = PlanType.Joint},
                new Employer{EmployerID = 23, EmployerName = "Employer 11", PlanType = PlanType.Joint},
                new Employer{EmployerID = 24, EmployerName = "Employer 12", PlanType = PlanType.Pension},
                new Employer{EmployerID = 25, EmployerName = "Employer 13", PlanType = PlanType.Joint},
                new Employer{EmployerID = 26, EmployerName = "Employer 14", PlanType = PlanType.Joint},
                new Employer{EmployerID = 27, EmployerName = "Employer 15", PlanType = PlanType.Joint},
                new Employer{EmployerID = 28, EmployerName = "Employer 16", PlanType = PlanType.Joint},
                new Employer{EmployerID = 35, EmployerName = "Employer 17", PlanType = PlanType.Joint},
                new Employer{EmployerID = 39, EmployerName = "Employer 18", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 41, EmployerName = "Employer 19", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 42, EmployerName = "Employer 20", PlanType = PlanType.Joint},
                new Employer{EmployerID = 44, EmployerName = "Employer 21", PlanType = PlanType.Joint},
                new Employer{EmployerID = 46, EmployerName = "Employer 22", PlanType = PlanType.Joint},
                new Employer{EmployerID = 47, EmployerName = "Employer 23", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 48, EmployerName = "Employer 24", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 50, EmployerName = "Employer 25", PlanType = PlanType.Joint},
                new Employer{EmployerID = 53, EmployerName = "Employer 26", PlanType = PlanType.Joint},
                new Employer{EmployerID = 55, EmployerName = "Employer 27", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 56, EmployerName = "Employer 28", PlanType = PlanType.Joint},
                new Employer{EmployerID = 59, EmployerName = "Employer 29", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 60, EmployerName = "Employer 30", PlanType = PlanType.Joint},
                new Employer{EmployerID = 61, EmployerName = "Employer 31", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 63, EmployerName = "Employer 32", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 65, EmployerName = "Employer 33", PlanType = PlanType.Benefits},
                new Employer{EmployerID = 66, EmployerName = "Employer 34", PlanType = PlanType.Joint},
                new Employer{EmployerID = 68, EmployerName = "Employer 35", PlanType = PlanType.Joint},
                new Employer{EmployerID = 73, EmployerName = "Employer 36", PlanType = PlanType.Pension},
                new Employer{EmployerID = 75, EmployerName = "Employer 37", PlanType = PlanType.Pension},
                new Employer{EmployerID = 76, EmployerName = "Employer 38", PlanType = PlanType.Pension},
            };
            employers.ForEach(s => context.Employers.Add(s));
            context.SaveChanges();
            
            var occupationCodes = new List<OccupationCode>
            {
                new OccupationCode{OccupationCodeID = 1, OccupationCodeName = "Occupation 01"},
                new OccupationCode{OccupationCodeID = 2, OccupationCodeName = "Occupation 02"},
                new OccupationCode{OccupationCodeID = 3, OccupationCodeName = "Occupation 03"},
                new OccupationCode{OccupationCodeID = 4, OccupationCodeName = "Occupation 04"},
                new OccupationCode{OccupationCodeID = 5, OccupationCodeName = "Occupation 05"},
                new OccupationCode{OccupationCodeID = 6, OccupationCodeName = "Occupation 06"},
                new OccupationCode{OccupationCodeID = 7, OccupationCodeName = "Occupation 07"},
                new OccupationCode{OccupationCodeID = 8, OccupationCodeName = "Occupation 08"},
                new OccupationCode{OccupationCodeID = 9, OccupationCodeName = "Occupation 09"},
                new OccupationCode{OccupationCodeID = 10, OccupationCodeName = "Occupation 10"},
                new OccupationCode{OccupationCodeID = 11, OccupationCodeName = "Occupation 11"},
                new OccupationCode{OccupationCodeID = 12, OccupationCodeName = "Occupation 12"},
                new OccupationCode{OccupationCodeID = 13, OccupationCodeName = "Occupation 13"},
                new OccupationCode{OccupationCodeID = 14, OccupationCodeName = "Occupation 14"},
                new OccupationCode{OccupationCodeID = 15, OccupationCodeName = "Occupation 15"},
                new OccupationCode{OccupationCodeID = 16, OccupationCodeName = "Occupation 16"},
                new OccupationCode{OccupationCodeID = 17, OccupationCodeName = "Occupation 17"},
                new OccupationCode{OccupationCodeID = 18, OccupationCodeName = "Occupation 18"},
                new OccupationCode{OccupationCodeID = 19, OccupationCodeName = "Occupation 19"},
                new OccupationCode{OccupationCodeID = 20, OccupationCodeName = "Occupation 20"},
                new OccupationCode{OccupationCodeID = 21, OccupationCodeName = "Occupation 21"},
                new OccupationCode{OccupationCodeID = 22, OccupationCodeName = "Occupation 22"},
                new OccupationCode{OccupationCodeID = 23, OccupationCodeName = "Occupation 23"},
                new OccupationCode{OccupationCodeID = 24, OccupationCodeName = "Occupation 24"},
                new OccupationCode{OccupationCodeID = 25, OccupationCodeName = "Occupation 25"},
                new OccupationCode{OccupationCodeID = 26, OccupationCodeName = "Occupation 26"},
                new OccupationCode{OccupationCodeID = 27, OccupationCodeName = "Occupation 27"},
                new OccupationCode{OccupationCodeID = 28, OccupationCodeName = "Occupation 28"},
                new OccupationCode{OccupationCodeID = 29, OccupationCodeName = "Occupation 29"},
                new OccupationCode{OccupationCodeID = 30, OccupationCodeName = "Occupation 30"},
                new OccupationCode{OccupationCodeID = 31, OccupationCodeName = "Occupation 31"},
                new OccupationCode{OccupationCodeID = 32, OccupationCodeName = "Occupation 32"},
                new OccupationCode{OccupationCodeID = 33, OccupationCodeName = "Occupation 33"},
                new OccupationCode{OccupationCodeID = 34, OccupationCodeName = "Occupation 34"},
                new OccupationCode{OccupationCodeID = 35, OccupationCodeName = "Occupation 35"},
                new OccupationCode{OccupationCodeID = 36, OccupationCodeName = "Occupation 36"},
                new OccupationCode{OccupationCodeID = 37, OccupationCodeName = "Occupation 37"},
                new OccupationCode{OccupationCodeID = 38, OccupationCodeName = "Occupation 38"},
                new OccupationCode{OccupationCodeID = 39, OccupationCodeName = "Occupation 39"},
                new OccupationCode{OccupationCodeID = 40, OccupationCodeName = "Occupation 40"},
                new OccupationCode{OccupationCodeID = 41, OccupationCodeName = "Occupation 41"},
                new OccupationCode{OccupationCodeID = 42, OccupationCodeName = "Occupation 42"},
                new OccupationCode{OccupationCodeID = 43, OccupationCodeName = "Occupation 43"},
                new OccupationCode{OccupationCodeID = 44, OccupationCodeName = "Occupation 44"},
                new OccupationCode{OccupationCodeID = 45, OccupationCodeName = "Occupation 45"},
                new OccupationCode{OccupationCodeID = 46, OccupationCodeName = "Occupation 46"},
                new OccupationCode{OccupationCodeID = 47, OccupationCodeName = "Occupation 47"},
                new OccupationCode{OccupationCodeID = 48, OccupationCodeName = "Occupation 48"},
                new OccupationCode{OccupationCodeID = 49, OccupationCodeName = "Occupation 49"},
                new OccupationCode{OccupationCodeID = 50, OccupationCodeName = "Occupation 50"},
                new OccupationCode{OccupationCodeID = 51, OccupationCodeName = "Occupation 51"},
                new OccupationCode{OccupationCodeID = 52, OccupationCodeName = "Occupation 52"},
                new OccupationCode{OccupationCodeID = 53, OccupationCodeName = "Occupation 53"},
                new OccupationCode{OccupationCodeID = 54, OccupationCodeName = "Occupation 54"},
                new OccupationCode{OccupationCodeID = 55, OccupationCodeName = "Occupation 55"},
                new OccupationCode{OccupationCodeID = 56, OccupationCodeName = "Occupation 56"},
                new OccupationCode{OccupationCodeID = 57, OccupationCodeName = "Occupation 57"},
                new OccupationCode{OccupationCodeID = 58, OccupationCodeName = "Occupation 58"},
                new OccupationCode{OccupationCodeID = 59, OccupationCodeName = "Occupation 59"},
                new OccupationCode{OccupationCodeID = 60, OccupationCodeName = "Occupation 60"},
                new OccupationCode{OccupationCodeID = 61, OccupationCodeName = "Occupation 61"},
                new OccupationCode{OccupationCodeID = 62, OccupationCodeName = "Occupation 62"},
                new OccupationCode{OccupationCodeID = 63, OccupationCodeName = "Occupation 63"},
                new OccupationCode{OccupationCodeID = 64, OccupationCodeName = "Occupation 64"},
                new OccupationCode{OccupationCodeID = 65, OccupationCodeName = "Occupation 65"},
                new OccupationCode{OccupationCodeID = 66, OccupationCodeName = "Occupation 66"},
                new OccupationCode{OccupationCodeID = 67, OccupationCodeName = "Occupation 67"},
                new OccupationCode{OccupationCodeID = 68, OccupationCodeName = "Occupation 68"},
                new OccupationCode{OccupationCodeID = 69, OccupationCodeName = "Occupation 69"},
                new OccupationCode{OccupationCodeID = 70, OccupationCodeName = "Occupation 70"},
                new OccupationCode{OccupationCodeID = 71, OccupationCodeName = "Occupation 71"},
                new OccupationCode{OccupationCodeID = 72, OccupationCodeName = "Occupation 72"},
                new OccupationCode{OccupationCodeID = 73, OccupationCodeName = "Occupation 73"},
                new OccupationCode{OccupationCodeID = 74, OccupationCodeName = "Occupation 74"},
                new OccupationCode{OccupationCodeID = 75, OccupationCodeName = "Occupation 75"},
                new OccupationCode{OccupationCodeID = 76, OccupationCodeName = "Occupation 76"},
                new OccupationCode{OccupationCodeID = 77, OccupationCodeName = "Occupation 77"},
                new OccupationCode{OccupationCodeID = 78, OccupationCodeName = "Occupation 78"},
                new OccupationCode{OccupationCodeID = 79, OccupationCodeName = "Occupation 79"},
                new OccupationCode{OccupationCodeID = 80, OccupationCodeName = "Occupation 80"},
                new OccupationCode{OccupationCodeID = 81, OccupationCodeName = "Occupation 81"},
                new OccupationCode{OccupationCodeID = 82, OccupationCodeName = "Occupation 82"},
                new OccupationCode{OccupationCodeID = 83, OccupationCodeName = "Occupation 83"},
                new OccupationCode{OccupationCodeID = 84, OccupationCodeName = "Occupation 84"},
                new OccupationCode{OccupationCodeID = 85, OccupationCodeName = "Occupation 85"},
                new OccupationCode{OccupationCodeID = 86, OccupationCodeName = "Occupation 86"},
                new OccupationCode{OccupationCodeID = 87, OccupationCodeName = "Occupation 87"},
                new OccupationCode{OccupationCodeID = 88, OccupationCodeName = "Occupation 88"},
                new OccupationCode{OccupationCodeID = 89, OccupationCodeName = "Occupation 89"},
                new OccupationCode{OccupationCodeID = 90, OccupationCodeName = "Occupation 90"},
                new OccupationCode{OccupationCodeID = 91, OccupationCodeName = "Occupation 91"},
                new OccupationCode{OccupationCodeID = 92, OccupationCodeName = "Occupation 92"},
                new OccupationCode{OccupationCodeID = 93, OccupationCodeName = "Occupation 93"},
                new OccupationCode{OccupationCodeID = 94, OccupationCodeName = "Occupation 94"},
                new OccupationCode{OccupationCodeID = 95, OccupationCodeName = "Occupation 95"},
                new OccupationCode{OccupationCodeID = 96, OccupationCodeName = "Occupation 96"},
                new OccupationCode{OccupationCodeID = 97, OccupationCodeName = "Occupation 97"},
                new OccupationCode{OccupationCodeID = 98, OccupationCodeName = "Occupation 98"},
                new OccupationCode{OccupationCodeID = 99, OccupationCodeName = "Occupation 99"},
            };
            occupationCodes.ForEach(s => context.OccupationCodes.Add(s));
            context.SaveChanges();
            
            var employerOccupationCodes = new List<EmployerOccupationCode>() {
                new EmployerOccupationCode{EmployerID = 35, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 55, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 55, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 41, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 41, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 41, OccupationCodeID = 80},
                new EmployerOccupationCode{EmployerID = 61, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 61, OccupationCodeID = 55},
                new EmployerOccupationCode{EmployerID = 61, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 61, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 61},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 82},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 43},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 24},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 64},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 10, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 63, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 35},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 48, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 63, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 39, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 72},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 93},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 94},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 86},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 76},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 27},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 28},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 37},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 49},
                new EmployerOccupationCode{EmployerID = 75, OccupationCodeID = 50},
                new EmployerOccupationCode{EmployerID = 16, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 16, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 16, OccupationCodeID = 78},
                new EmployerOccupationCode{EmployerID = 16, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 47, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 47, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 47, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 47, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 42, OccupationCodeID = 19},
                new EmployerOccupationCode{EmployerID = 42, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 42, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 76},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 21},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 20, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 19, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 19, OccupationCodeID = 87},
                new EmployerOccupationCode{EmployerID = 19, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 90},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 23, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 23, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 23, OccupationCodeID = 39},
                new EmployerOccupationCode{EmployerID = 23, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 65, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 65, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 65, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 65, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 65, OccupationCodeID = 6},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 98},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 38},
                new EmployerOccupationCode{EmployerID = 53, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 53, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 53, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 50, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 50, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 50, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 50, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 60, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 60, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 60, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 66, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 66, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 66, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 76, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 76, OccupationCodeID = 62},
                new EmployerOccupationCode{EmployerID = 76, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 76, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 93},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 76},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 90},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 76},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 56, OccupationCodeID = 93},
                new EmployerOccupationCode{EmployerID = 59, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 59, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 80},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 88},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 85},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 99},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 87},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 40},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 39},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 25},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 24, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 46, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 46, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 46, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 46, OccupationCodeID = 21},
                new EmployerOccupationCode{EmployerID = 46, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 25, OccupationCodeID = 26},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 44, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 68, OccupationCodeID = 6},
                new EmployerOccupationCode{EmployerID = 68, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 68, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 68, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 45},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 24},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 84},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 22, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 50},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 49},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 37},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 27},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 28},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 86},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 76},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 93},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 94},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 72},
                new EmployerOccupationCode{EmployerID = 73, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 57},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 38},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 14},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 13},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 30},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 29},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 44},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 80},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 27, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 30},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 57},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 13},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 29},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 14},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 80},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 44},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 11, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 32},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 33},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 31},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 29},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 30},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 66},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 34},
                new EmployerOccupationCode{EmployerID = 7, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 87},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 87},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 81},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 51},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 28, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 21},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 1},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 56},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 18},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 21},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 65},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 1},
                new EmployerOccupationCode{EmployerID = 17, OccupationCodeID = 60},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 95},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 78},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 90},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 10},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 95},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 78},
                new EmployerOccupationCode{EmployerID = 4, OccupationCodeID = 90},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 90},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 11},
                new EmployerOccupationCode{EmployerID = 9, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 7},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 9},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 59},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 4},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 16},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 38},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 98},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 2},
                new EmployerOccupationCode{EmployerID = 26, OccupationCodeID = 11},
            };
            employerOccupationCodes.ForEach(s => context.EmployerOccupationCodes.Add(s));
            context.SaveChanges();

            var workStatuses = new List<WorkStatus>
            {
                new WorkStatus{WorkStatusID = 1, WorkStatusName = "Full-time"},
                new WorkStatus{WorkStatusID = 2, WorkStatusName = "Part-time"},
                new WorkStatus{WorkStatusID = 4, WorkStatusName = "Per diem"}
            };
            workStatuses.ForEach(s => context.WorkStatuses.Add(s));
            context.SaveChanges();

            var wizardProgresses = new List<WizardProgress>
            {
                new WizardProgress{WizardProgressID = 1, Sequence = 1, ActionResult = "CreateParticipantPerson"},
                new WizardProgress{WizardProgressID = 2, Sequence = 2, ActionResult = "AddCurrentEmployer"},
                new WizardProgress{WizardProgressID = 3, Sequence = 3, ActionResult = "AddPreviousEmployer"},
                new WizardProgress{WizardProgressID = 4, Sequence = 4, ActionResult = "SetMaritalStatus"},
                new WizardProgress{WizardProgressID = 5, Sequence = 5, ActionResult = "AddCurrentSpouse"},
                new WizardProgress{WizardProgressID = 6, Sequence = 6, ActionResult = "AddDivorceSpouse"},
                new WizardProgress{WizardProgressID = 7, Sequence = 7, ActionResult = "AddDeceaseSpouse"},
                new WizardProgress{WizardProgressID = 8, Sequence = 9, ActionResult = "AddChild"},
                new WizardProgress{WizardProgressID = 9, Sequence = 12, ActionResult = "AddNewBeneficiary"},
                new WizardProgress{WizardProgressID = 10, Sequence = 13, ActionResult = "Portal"},
                new WizardProgress{WizardProgressID = 11, Sequence = 8, ActionResult = "SetChildStatus"},
                new WizardProgress{WizardProgressID = 12, Sequence = 10, ActionResult = "AddBeneficiaryType"},
                new WizardProgress{WizardProgressID = 13, Sequence = 11, ActionResult = "AddExistingBeneficiary"}
            };
            wizardProgresses.ForEach(s => context.WizardProgresses.Add(s));
            context.SaveChanges();

#if DEBUG
            //var addresses = new List<Address>
            //{
            //    new Address{AddressID = 1, Address1 = "58 Egmont Court", City = "Delmar", StateID = 31, 
            //        ZipCode = "12054"},

            //    new Address{AddressID = 2, Address1 = "11 Goethe Street", Address2 = "Second Floor", 
            //        City = "Albany", StateID = 31, ZipCode = "13902"},

            //    new Address{AddressID = 3, Address1 = "11 Goethe Street", Address2 = "First Floor", 
            //        City = "Albany", StateID = 31, ZipCode = "13902"},

            //    new Address{AddressID = 4, Address1 = "11 Goethe Street", Address2 = "Third Floor", 
            //        City = "Albany", StateID = 31, ZipCode = "13902"}
            //};
            //addresses.ForEach(s => context.Addresses.Add(s));
            //context.SaveChanges();

            //var people = new List<Person>
            //{
            //    new Person{PersonID = 1, FirstName = "Connor", MiddleInitial = "J", LastName = "Stutsrim", 
            //        BirthDate = DateTime.Parse("01/01/1994"), SSN = "111-22-3333", GenderID = 1, AddressID = 1, 
            //        HomePhone = "5184751212", CellPhone = "5189357846", Email = "connorsttsrm@email.com"},

            //    new Person{PersonID = 2, FirstName = "Colin", MiddleInitial = "D", LastName = "Leath", 
            //        BirthDate = DateTime.Parse("01/01/1994"), SSN = "333-22-4444", GenderID = 1, AddressID = 3, 
            //        HomePhone = "1234567890", CellPhone = "0123456789", Email = "cdleath@email.com"},

            //    new Person{PersonID = 3, FirstName = "Taylor", MiddleInitial = "Q", LastName = "Scranton", 
            //        BirthDate = DateTime.Parse("01/01/1994"), SSN = "123-45-6789", GenderID = 1, AddressID = 2, 
            //        HomePhone = "1597534568", CellPhone = "1472583690", Email = "tscrant1@email.com"},

            //    new Person{PersonID = 4, FirstName = "Cara", MiddleInitial = "X", LastName = "Natale", 
            //        BirthDate = DateTime.Parse("01/01/1994"), SSN = "420-69-1379", GenderID = 2, AddressID = 3, 
            //        HomePhone = "9638527410", CellPhone = "0258789456", Email = "cnatale1@email.com"},

            //    new Person{PersonID = 5, FirstName = "Aaron", MiddleInitial = "X", LastName = "Miner", 
            //        BirthDate = DateTime.Parse("01/01/1994"), SSN = "420-69-1379", GenderID = 1, AddressID = 4, 
            //        HomePhone = "9638527410", CellPhone = "0258789456", Email = "aminer1@email.com"}
            //};
            //people.ForEach(s => context.People.Add(s));
            //context.SaveChanges();

            //var employmentInformation = new List<EmploymentInformation>
            //{
            //    new EmploymentInformation{EmploymentInformationID = 1, EmployerID = 1, Employer = context.Employers.Find(1), 
            //        HireDate = DateTime.Parse("01/01/2010"), WorkStatusID = 3, WorkHours = 1 ,
            //        WorkStatus = context.WorkStatuses.Find(3), OccupationCodeID = 5, OccupationCode = context.OccupationCodes.Find(5)},
            //    new EmploymentInformation{EmploymentInformationID = 2, EmployerID = 2, Employer = context.Employers.Find(2), 
            //        HireDate = DateTime.Parse("01/01/2010"), WorkStatusID = 2, WorkHours = 20,  
            //        WorkStatus = context.WorkStatuses.Find(2), OccupationCodeID = 4, OccupationCode = context.OccupationCodes.Find(4)},
            //    new EmploymentInformation{EmploymentInformationID = 3, EmployerID = 3, Employer = context.Employers.Find(3),
            //        HireDate = DateTime.Parse("01/01/2010"), WorkStatusID = 1, WorkHours = 40,  
            //        WorkStatus = context.WorkStatuses.Find(1), OccupationCodeID = 3, OccupationCode = context.OccupationCodes.Find(3)},
            //    new EmploymentInformation{EmploymentInformationID = 4, EmployerID = 2, Employer = context.Employers.Find(2),
            //        HireDate = DateTime.Parse("01/01/2010"), WorkStatusID = 2, WorkHours = 20,  
            //        WorkStatus = context.WorkStatuses.Find(2), OccupationCodeID = 2, OccupationCode = context.OccupationCodes.Find(2)},
            //    new EmploymentInformation{EmploymentInformationID = 5, EmployerID = 1, Employer = context.Employers.Find(1),
            //        HireDate = DateTime.Parse("01/01/2010"), WorkStatusID = 3, WorkHours = 2,  
            //        WorkStatus = context.WorkStatuses.Find(3), OccupationCodeID = 1, OccupationCode = context.OccupationCodes.Find(1)}
            //};
            //employmentInformation.ForEach(s => context.EmploymentInformation.Add(s));
            //context.SaveChanges();

            //var participants = new List<Participant>
            //{
            //    new Participant{PersonID = 1, EmployerID = 2, WizardProgressID = 1},
            //    new Participant{PersonID = 2, EmployerID = 1, WizardProgressID = 2},
            //    new Participant{PersonID = 3, EmployerID = 1, WizardProgressID = 3},
            //    new Participant{PersonID = 4, EmployerID = 2, WizardProgressID = 4},
            //    new Participant{PersonID = 5, EmployerID = 3, WizardProgressID = 5}
            //};
            //participants.ForEach(s => context.Participants.Add(s));
            //context.SaveChanges();

            //var beneficiaries = new List<Beneficiary>
            //{
            //    new Beneficiary{BeneficiaryID = 1, PersonID = 2, RelationshipTypeID = 1, ParticipantID = 4},
            //    new Beneficiary{BeneficiaryID = 2, PersonID = 4, RelationshipTypeID = 2, ParticipantID = 2}
            //};
            //beneficiaries.ForEach(s => context.Beneficiaries.Add(s));
            //context.SaveChanges();

            //var dependents = new List<Dependent>
            //{
            //    new Dependent{DependentID = 1, PersonID = 2, ParticipantID = 4},
            //    new Dependent{DependentID = 2, PersonID = 4, ParticipantID = 2}
            //};
            //dependents.ForEach(s => context.Dependents.Add(s));
            //context.SaveChanges();
#endif

        }
    }
}